//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Tesla.DataAccess {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class RoboSepProtocol {
        
        private header headerField;
        
        private constraints constraintsField;
        
        private commands commandsField;
        
        private customNames[] customNamesField;
        
        private multipleSamples multipleSamplesField;
        
        private resultVialChecks[] resultVialChecksField;
        
        private vialBarcodes[] vialBarcodesField;
        
        private RoboSepProtocolType typeField;
        
        /// <remarks/>
        public header header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public constraints constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        public commands commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customNames")]
        public customNames[] customNames {
            get {
                return this.customNamesField;
            }
            set {
                this.customNamesField = value;
            }
        }
        
        /// <remarks/>
        public multipleSamples multipleSamples {
            get {
                return this.multipleSamplesField;
            }
            set {
                this.multipleSamplesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultVialChecks")]
        public resultVialChecks[] resultVialChecks {
            get {
                return this.resultVialChecksField;
            }
            set {
                this.resultVialChecksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vialBarcodes")]
        public vialBarcodes[] vialBarcodes {
            get {
                return this.vialBarcodesField;
            }
            set {
                this.vialBarcodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RoboSepProtocolType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class header {
        
        private date dateField;
        
        private author authorField;
        
        private robosep robosepField;
        
        private workaround workaroundField;
        
        private versionInfo versionInfoField;
        
        private string labelField;
        
        private string versionField;
        
        private string descriptionField;
        
        private string protocolNum1Field;
        
        private string protocolNum2Field;
        
        private bool protocolDescriptionManualFillField;
        
        private bool protocolDescriptionManualFillFieldSpecified;
        
        /// <remarks/>
        public date date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public author author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public robosep robosep {
            get {
                return this.robosepField;
            }
            set {
                this.robosepField = value;
            }
        }
        
        /// <remarks/>
        public workaround workaround {
            get {
                return this.workaroundField;
            }
            set {
                this.workaroundField = value;
            }
        }
        
        /// <remarks/>
        public versionInfo versionInfo {
            get {
                return this.versionInfoField;
            }
            set {
                this.versionInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocolNum1 {
            get {
                return this.protocolNum1Field;
            }
            set {
                this.protocolNum1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocolNum2 {
            get {
                return this.protocolNum2Field;
            }
            set {
                this.protocolNum2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ProtocolDescriptionManualFill {
            get {
                return this.protocolDescriptionManualFillField;
            }
            set {
                this.protocolDescriptionManualFillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProtocolDescriptionManualFillSpecified {
            get {
                return this.protocolDescriptionManualFillFieldSpecified;
            }
            set {
                this.protocolDescriptionManualFillFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class date {
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private bool modifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedSpecified {
            get {
                return this.modifiedFieldSpecified;
            }
            set {
                this.modifiedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VolumeCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VolumeMaintenanceCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WaitCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceCommandType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="STI")]
    public partial class CommandType {
        
        private string seqField;
        
        private string labelField;
        
        private string extensionTimeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string extensionTime {
            get {
                return this.extensionTimeField;
            }
            set {
                this.extensionTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VolumeMaintenanceCommandType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="STI")]
    public partial class VolumeCommandType : CommandType {
        
        private vials vialsField;
        
        private vials2 vials2Field;
        
        private vials3 vials3Field;
        
        private object itemField;
        
        private object item1Field;
        
        private object item2Field;
        
        private object item3Field;
        
        private object item4Field;
        
        private int tipRackField;
        
        private bool tipRackFieldSpecified;
        
        private int numOfStagesField;
        
        private bool numOfStagesFieldSpecified;
        
        /// <remarks/>
        public vials vials {
            get {
                return this.vialsField;
            }
            set {
                this.vialsField = value;
            }
        }
        
        /// <remarks/>
        public vials2 vials2 {
            get {
                return this.vials2Field;
            }
            set {
                this.vials2Field = value;
            }
        }
        
        /// <remarks/>
        public vials3 vials3 {
            get {
                return this.vials3Field;
            }
            set {
                this.vials3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("absoluteVolume", typeof(absoluteVolume))]
        [System.Xml.Serialization.XmlElementAttribute("relativeVolume", typeof(relativeVolume))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("absoluteVolume2", typeof(absoluteVolume2))]
        [System.Xml.Serialization.XmlElementAttribute("relativeVolume2", typeof(relativeVolume2))]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("absoluteVolume3", typeof(absoluteVolume3))]
        [System.Xml.Serialization.XmlElementAttribute("relativeVolume3", typeof(relativeVolume3))]
        public object Item2 {
            get {
                return this.item2Field;
            }
            set {
                this.item2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("absoluteVolume4", typeof(absoluteVolume4))]
        [System.Xml.Serialization.XmlElementAttribute("relativeVolume4", typeof(relativeVolume4))]
        public object Item3 {
            get {
                return this.item3Field;
            }
            set {
                this.item3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("absoluteVolume5", typeof(absoluteVolume5))]
        [System.Xml.Serialization.XmlElementAttribute("relativeVolume5", typeof(relativeVolume5))]
        public object Item4 {
            get {
                return this.item4Field;
            }
            set {
                this.item4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int tipRack {
            get {
                return this.tipRackField;
            }
            set {
                this.tipRackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipRackSpecified {
            get {
                return this.tipRackFieldSpecified;
            }
            set {
                this.tipRackFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numOfStages {
            get {
                return this.numOfStagesField;
            }
            set {
                this.numOfStagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numOfStagesSpecified {
            get {
                return this.numOfStagesFieldSpecified;
            }
            set {
                this.numOfStagesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class vials {
        
        private string srcField;
        
        private string destField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class vials2 {
        
        private string srcField;
        
        private string destField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class vials3 {
        
        private string srcField;
        
        private string destField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class absoluteVolume {
        
        private string value_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string value_uL {
            get {
                return this.value_uLField;
            }
            set {
                this.value_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class relativeVolume {
        
        private decimal proportionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal proportion {
            get {
                return this.proportionField;
            }
            set {
                this.proportionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class absoluteVolume2 {
        
        private string value_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string value_uL {
            get {
                return this.value_uLField;
            }
            set {
                this.value_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class relativeVolume2 {
        
        private decimal proportionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal proportion {
            get {
                return this.proportionField;
            }
            set {
                this.proportionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class absoluteVolume3 {
        
        private string value_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string value_uL {
            get {
                return this.value_uLField;
            }
            set {
                this.value_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class relativeVolume3 {
        
        private decimal proportionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal proportion {
            get {
                return this.proportionField;
            }
            set {
                this.proportionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class absoluteVolume4 {
        
        private string value_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string value_uL {
            get {
                return this.value_uLField;
            }
            set {
                this.value_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class relativeVolume4 {
        
        private decimal proportionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal proportion {
            get {
                return this.proportionField;
            }
            set {
                this.proportionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class absoluteVolume5 {
        
        private string value_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string value_uL {
            get {
                return this.value_uLField;
            }
            set {
                this.value_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class relativeVolume5 {
        
        private decimal proportionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal proportion {
            get {
                return this.proportionField;
            }
            set {
                this.proportionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="STI")]
    public partial class VolumeMaintenanceCommandType : VolumeCommandType {
        
        private flags flagsField;
        
        /// <remarks/>
        public flags flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class flags {
        
        private bool homeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="STI")]
    public partial class WaitCommandType : CommandType {
        
        private processingTime processingTimeField;
        
        /// <remarks/>
        public processingTime processingTime {
            get {
                return this.processingTimeField;
            }
            set {
                this.processingTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class processingTime {
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="STI")]
    public partial class ServiceCommandType : CommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class author {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class robosep {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class workaround {
        
        private string absoluteVolMultiplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string absoluteVolMultiplier {
            get {
                return this.absoluteVolMultiplierField;
            }
            set {
                this.absoluteVolMultiplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class versionInfo {
        
        private string protocolRevisionField;
        
        private string protocolEditorVersionField;
        
        private string protocolEditorINIVersionField;
        
        private string platformField;
        
        private string protocolFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string protocolRevision {
            get {
                return this.protocolRevisionField;
            }
            set {
                this.protocolRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocolEditorVersion {
            get {
                return this.protocolEditorVersionField;
            }
            set {
                this.protocolEditorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocolEditorINIVersion {
            get {
                return this.protocolEditorINIVersionField;
            }
            set {
                this.protocolEditorINIVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocolFormat {
            get {
                return this.protocolFormatField;
            }
            set {
                this.protocolFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class constraints {
        
        private quadrants quadrantsField;
        
        private sampleVolume sampleVolumeField;
        
        private workingVolume workingVolumeField;
        
        private feature[] featuresSwitchesField;
        
        /// <remarks/>
        public quadrants quadrants {
            get {
                return this.quadrantsField;
            }
            set {
                this.quadrantsField = value;
            }
        }
        
        /// <remarks/>
        public sampleVolume sampleVolume {
            get {
                return this.sampleVolumeField;
            }
            set {
                this.sampleVolumeField = value;
            }
        }
        
        /// <remarks/>
        public workingVolume workingVolume {
            get {
                return this.workingVolumeField;
            }
            set {
                this.workingVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("feature", IsNullable=false)]
        public feature[] featuresSwitches {
            get {
                return this.featuresSwitchesField;
            }
            set {
                this.featuresSwitchesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class quadrants {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class sampleVolume {
        
        private string min_uLField;
        
        private string max_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string min_uL {
            get {
                return this.min_uLField;
            }
            set {
                this.min_uLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string max_uL {
            get {
                return this.max_uLField;
            }
            set {
                this.max_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class workingVolume {
        
        private string sampleThreshold_uLField;
        
        private string lowVolume_uLField;
        
        private string highVolume_uLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string sampleThreshold_uL {
            get {
                return this.sampleThreshold_uLField;
            }
            set {
                this.sampleThreshold_uLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string lowVolume_uL {
            get {
                return this.lowVolume_uLField;
            }
            set {
                this.lowVolume_uLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string highVolume_uL {
            get {
                return this.highVolume_uLField;
            }
            set {
                this.highVolume_uLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class feature {
        
        private string nameField;
        
        private string descField;
        
        private string inputTypeField;
        
        private string inputDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string inputType {
            get {
                return this.inputTypeField;
            }
            set {
                this.inputTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string inputData {
            get {
                return this.inputDataField;
            }
            set {
                this.inputDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class commands {
        
        private CommandType[] itemsField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DemoCommand", typeof(DemoCommand))]
        [System.Xml.Serialization.XmlElementAttribute("FlushCommand", typeof(FlushCommand))]
        [System.Xml.Serialization.XmlElementAttribute("HomeAllCommand", typeof(HomeAllCommand))]
        [System.Xml.Serialization.XmlElementAttribute("IncubateCommand", typeof(IncubateCommand))]
        [System.Xml.Serialization.XmlElementAttribute("MixCommand", typeof(MixCommand))]
        [System.Xml.Serialization.XmlElementAttribute("MixTransCommand", typeof(MixTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("PauseCommand", typeof(PauseCommand))]
        [System.Xml.Serialization.XmlElementAttribute("PrimeCommand", typeof(PrimeCommand))]
        [System.Xml.Serialization.XmlElementAttribute("PumpLifeCommand", typeof(PumpLifeCommand))]
        [System.Xml.Serialization.XmlElementAttribute("ResusMixCommand", typeof(ResusMixCommand))]
        [System.Xml.Serialization.XmlElementAttribute("ResusMixSepTransCommand", typeof(ResusMixSepTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("ResuspendVialCommand", typeof(ResuspendVialCommand))]
        [System.Xml.Serialization.XmlElementAttribute("SeparateCommand", typeof(SeparateCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TopUpMixTransCommand", typeof(TopUpMixTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TopUpMixTransSepTransCommand", typeof(TopUpMixTransSepTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TopUpTransCommand", typeof(TopUpTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TopUpTransSepTransCommand", typeof(TopUpTransSepTransCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TopUpVialCommand", typeof(TopUpVialCommand))]
        [System.Xml.Serialization.XmlElementAttribute("TransportCommand", typeof(TransportCommand))]
        public CommandType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class DemoCommand : ServiceCommandType {
        
        private string iterationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string iterations {
            get {
                return this.iterationsField;
            }
            set {
                this.iterationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class FlushCommand : VolumeMaintenanceCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class HomeAllCommand : ServiceCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class IncubateCommand : WaitCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class MixCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class MixTransCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class PauseCommand : WaitCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class PrimeCommand : VolumeMaintenanceCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class PumpLifeCommand : ServiceCommandType {
        
        private string iterationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string iterations {
            get {
                return this.iterationsField;
            }
            set {
                this.iterationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class ResusMixCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class ResusMixSepTransCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class ResuspendVialCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class SeparateCommand : WaitCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TopUpMixTransCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TopUpMixTransSepTransCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TopUpTransCommand : VolumeCommandType {
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TopUpTransSepTransCommand : VolumeCommandType {
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TopUpVialCommand : VolumeCommandType {
        
        private string mixCyclesField;
        
        private string tipTubeBottomGapField;
        
        private bool freeAirDispenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string mixCycles {
            get {
                return this.mixCyclesField;
            }
            set {
                this.mixCyclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string tipTubeBottomGap {
            get {
                return this.tipTubeBottomGapField;
            }
            set {
                this.tipTubeBottomGapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class TransportCommand : VolumeCommandType {
        
        private bool freeAirDispenseField;
        
        private bool useBufferTipField;
        
        private bool useBufferTipFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool freeAirDispense {
            get {
                return this.freeAirDispenseField;
            }
            set {
                this.freeAirDispenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useBufferTip {
            get {
                return this.useBufferTipField;
            }
            set {
                this.useBufferTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useBufferTipSpecified {
            get {
                return this.useBufferTipFieldSpecified;
            }
            set {
                this.useBufferTipFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class customNames {
        
        private string sampleTubeField;
        
        private string bufferBottleField;
        
        private string separationTubeField;
        
        private string wasteTubeField;
        
        private string magneticParticleVialField;
        
        private string selectionCocktailVialField;
        
        private string antibodyCocktailVialField;
        
        private string lysisBufferTubeField;
        
        private string bufferBottle34Field;
        
        private string bufferBottle56Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sampleTube {
            get {
                return this.sampleTubeField;
            }
            set {
                this.sampleTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bufferBottle {
            get {
                return this.bufferBottleField;
            }
            set {
                this.bufferBottleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string separationTube {
            get {
                return this.separationTubeField;
            }
            set {
                this.separationTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wasteTube {
            get {
                return this.wasteTubeField;
            }
            set {
                this.wasteTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string magneticParticleVial {
            get {
                return this.magneticParticleVialField;
            }
            set {
                this.magneticParticleVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selectionCocktailVial {
            get {
                return this.selectionCocktailVialField;
            }
            set {
                this.selectionCocktailVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string antibodyCocktailVial {
            get {
                return this.antibodyCocktailVialField;
            }
            set {
                this.antibodyCocktailVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lysisBufferTube {
            get {
                return this.lysisBufferTubeField;
            }
            set {
                this.lysisBufferTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bufferBottle34 {
            get {
                return this.bufferBottle34Field;
            }
            set {
                this.bufferBottle34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bufferBottle56 {
            get {
                return this.bufferBottle56Field;
            }
            set {
                this.bufferBottle56Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class multipleSamples {
        
        private bool q1Field;
        
        private bool q1FieldSpecified;
        
        private bool q2Field;
        
        private bool q2FieldSpecified;
        
        private bool q3Field;
        
        private bool q3FieldSpecified;
        
        private bool q4Field;
        
        private bool q4FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Q1 {
            get {
                return this.q1Field;
            }
            set {
                this.q1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Q1Specified {
            get {
                return this.q1FieldSpecified;
            }
            set {
                this.q1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Q2 {
            get {
                return this.q2Field;
            }
            set {
                this.q2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Q2Specified {
            get {
                return this.q2FieldSpecified;
            }
            set {
                this.q2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Q3 {
            get {
                return this.q3Field;
            }
            set {
                this.q3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Q3Specified {
            get {
                return this.q3FieldSpecified;
            }
            set {
                this.q3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Q4 {
            get {
                return this.q4Field;
            }
            set {
                this.q4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Q4Specified {
            get {
                return this.q4FieldSpecified;
            }
            set {
                this.q4FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class resultVialChecks {
        
        private bool sampleTubeField;
        
        private bool sampleTubeFieldSpecified;
        
        private bool bufferBottleField;
        
        private bool bufferBottleFieldSpecified;
        
        private bool separationTubeField;
        
        private bool separationTubeFieldSpecified;
        
        private bool wasteTubeField;
        
        private bool wasteTubeFieldSpecified;
        
        private bool magneticParticleVialField;
        
        private bool magneticParticleVialFieldSpecified;
        
        private bool selectionCocktailVialField;
        
        private bool selectionCocktailVialFieldSpecified;
        
        private bool antibodyCocktailVialField;
        
        private bool antibodyCocktailVialFieldSpecified;
        
        private bool lysisBufferTubeField;
        
        private bool lysisBufferTubeFieldSpecified;
        
        private bool bufferBottle34Field;
        
        private bool bufferBottle34FieldSpecified;
        
        private bool bufferBottle56Field;
        
        private bool bufferBottle56FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool sampleTube {
            get {
                return this.sampleTubeField;
            }
            set {
                this.sampleTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sampleTubeSpecified {
            get {
                return this.sampleTubeFieldSpecified;
            }
            set {
                this.sampleTubeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool bufferBottle {
            get {
                return this.bufferBottleField;
            }
            set {
                this.bufferBottleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bufferBottleSpecified {
            get {
                return this.bufferBottleFieldSpecified;
            }
            set {
                this.bufferBottleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool separationTube {
            get {
                return this.separationTubeField;
            }
            set {
                this.separationTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool separationTubeSpecified {
            get {
                return this.separationTubeFieldSpecified;
            }
            set {
                this.separationTubeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool wasteTube {
            get {
                return this.wasteTubeField;
            }
            set {
                this.wasteTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wasteTubeSpecified {
            get {
                return this.wasteTubeFieldSpecified;
            }
            set {
                this.wasteTubeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool magneticParticleVial {
            get {
                return this.magneticParticleVialField;
            }
            set {
                this.magneticParticleVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magneticParticleVialSpecified {
            get {
                return this.magneticParticleVialFieldSpecified;
            }
            set {
                this.magneticParticleVialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool selectionCocktailVial {
            get {
                return this.selectionCocktailVialField;
            }
            set {
                this.selectionCocktailVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selectionCocktailVialSpecified {
            get {
                return this.selectionCocktailVialFieldSpecified;
            }
            set {
                this.selectionCocktailVialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool antibodyCocktailVial {
            get {
                return this.antibodyCocktailVialField;
            }
            set {
                this.antibodyCocktailVialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool antibodyCocktailVialSpecified {
            get {
                return this.antibodyCocktailVialFieldSpecified;
            }
            set {
                this.antibodyCocktailVialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lysisBufferTube {
            get {
                return this.lysisBufferTubeField;
            }
            set {
                this.lysisBufferTubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lysisBufferTubeSpecified {
            get {
                return this.lysisBufferTubeFieldSpecified;
            }
            set {
                this.lysisBufferTubeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool bufferBottle34 {
            get {
                return this.bufferBottle34Field;
            }
            set {
                this.bufferBottle34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bufferBottle34Specified {
            get {
                return this.bufferBottle34FieldSpecified;
            }
            set {
                this.bufferBottle34FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool bufferBottle56 {
            get {
                return this.bufferBottle56Field;
            }
            set {
                this.bufferBottle56Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bufferBottle56Specified {
            get {
                return this.bufferBottle56FieldSpecified;
            }
            set {
                this.bufferBottle56FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class vialBarcodes {
        
        private string quadrantField;
        
        private string squareVialBarcodeField;
        
        private string circleVialBarcodeField;
        
        private string triangleVialBarcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string quadrant {
            get {
                return this.quadrantField;
            }
            set {
                this.quadrantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string squareVialBarcode {
            get {
                return this.squareVialBarcodeField;
            }
            set {
                this.squareVialBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string circleVialBarcode {
            get {
                return this.circleVialBarcodeField;
            }
            set {
                this.circleVialBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string triangleVialBarcode {
            get {
                return this.triangleVialBarcodeField;
            }
            set {
                this.triangleVialBarcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    public enum RoboSepProtocolType {
        
        /// <remarks/>
        Positive,
        
        /// <remarks/>
        Negative,
        
        /// <remarks/>
        HumanPositive,
        
        /// <remarks/>
        MousePositive,
        
        /// <remarks/>
        HumanNegative,
        
        /// <remarks/>
        MouseNegative,
        
        /// <remarks/>
        WholeBloodPositive,
        
        /// <remarks/>
        WholeBloodNegative,
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Maintenance,
        
        /// <remarks/>
        Shutdown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="STI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="STI", IsNullable=false)]
    public partial class featuresSwitches {
        
        private feature[] featureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public feature[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
    }
}
