//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Back_CLICK {
            get {
                object obj = ResourceManager.GetObject("Back_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BACK_OVER {
            get {
                object obj = ResourceManager.GetObject("BACK_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BACK_STD {
            get {
                object obj = ResourceManager.GetObject("BACK_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Background_Resources {
            get {
                object obj = ResourceManager.GetObject("Background_Resources", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap barcode_header {
            get {
                object obj = ResourceManager.GetObject("barcode_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_EditProtocolList {
            get {
                object obj = ResourceManager.GetObject("BG_EditProtocolList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_ProtocolSelection {
            get {
                object obj = ResourceManager.GetObject("BG_ProtocolSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_Resources1 {
            get {
                object obj = ResourceManager.GetObject("BG_Resources1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_RunLog {
            get {
                object obj = ResourceManager.GetObject("BG_RunLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_UserProtocolList {
            get {
                object obj = ResourceManager.GetObject("BG_UserProtocolList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bottle {
            get {
                object obj = ResourceManager.GetObject("bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnDROPBOX_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnDROPBOX_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnDROPBOX_STD {
            get {
                object obj = ResourceManager.GetObject("btnDROPBOX_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnHeader_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_CLICK1 {
            get {
                object obj = ResourceManager.GetObject("btnHeader_CLICK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_OVER {
            get {
                object obj = ResourceManager.GetObject("btnHeader_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_OVER1 {
            get {
                object obj = ResourceManager.GetObject("btnHeader_OVER1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_STD {
            get {
                object obj = ResourceManager.GetObject("btnHeader_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnHeader_STD1 {
            get {
                object obj = ResourceManager.GetObject("btnHeader_STD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnLG_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnLG_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnLG_STD {
            get {
                object obj = ResourceManager.GetObject("btnLG_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnMed_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnMed_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnMed_STD {
            get {
                object obj = ResourceManager.GetObject("btnMed_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnPlay_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnPlay_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnPlay_STD {
            get {
                object obj = ResourceManager.GetObject("btnPlay_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnRED_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnRED_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnRED_STD {
            get {
                object obj = ResourceManager.GetObject("btnRED_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnsmall_CLICK {
            get {
                object obj = ResourceManager.GetObject("btnsmall_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnsmall_STD {
            get {
                object obj = ResourceManager.GetObject("btnsmall_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cancel_STD {
            get {
                object obj = ResourceManager.GetObject("Cancel_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cancel_STD1 {
            get {
                object obj = ResourceManager.GetObject("Cancel_STD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap carousel_104x86_CLICK {
            get {
                object obj = ResourceManager.GetObject("carousel_104x86_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap carousel_104x86_DISABLE {
            get {
                object obj = ResourceManager.GetObject("carousel_104x86_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap carousel_104x86_OVER {
            get {
                object obj = ResourceManager.GetObject("carousel_104x86_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap carousel_104x86_STD {
            get {
                object obj = ResourceManager.GetObject("carousel_104x86_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap carousel_34x34 {
            get {
                object obj = ResourceManager.GetObject("carousel_34x34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CustomUserPic_Border {
            get {
                object obj = ResourceManager.GetObject("CustomUserPic_Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultUser_BLUE {
            get {
                object obj = ResourceManager.GetObject("DefaultUser_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultUser_GREEN {
            get {
                object obj = ResourceManager.GetObject("DefaultUser_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultUser_GREY {
            get {
                object obj = ResourceManager.GetObject("DefaultUser_GREY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultUser_PURPLE {
            get {
                object obj = ResourceManager.GetObject("DefaultUser_PURPLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DefaultUserPlus_PURPLE {
            get {
                object obj = ResourceManager.GetObject("DefaultUserPlus_PURPLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbBack_CLICK {
            get {
                object obj = ResourceManager.GetObject("fbBack_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbBack_OVER {
            get {
                object obj = ResourceManager.GetObject("fbBack_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbBack_STD {
            get {
                object obj = ResourceManager.GetObject("fbBack_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbNewDir_Click {
            get {
                object obj = ResourceManager.GetObject("fbNewDir_Click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbNewDir_OVER {
            get {
                object obj = ResourceManager.GetObject("fbNewDir_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbNewDir_STD {
            get {
                object obj = ResourceManager.GetObject("fbNewDir_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbRefresh_CLICK {
            get {
                object obj = ResourceManager.GetObject("fbRefresh_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbRefresh_OVER {
            get {
                object obj = ResourceManager.GetObject("fbRefresh_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbRefresh_STD {
            get {
                object obj = ResourceManager.GetObject("fbRefresh_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbUp_CLICK {
            get {
                object obj = ResourceManager.GetObject("fbUp_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbUp_OVER {
            get {
                object obj = ResourceManager.GetObject("fbUp_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbUp_STD {
            get {
                object obj = ResourceManager.GetObject("fbUp_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Female75x75 {
            get {
                object obj = ResourceManager.GetObject("Female75x75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Frame {
            get {
                object obj = ResourceManager.GetObject("Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN03M_up_arrow_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN03M_up_arrow_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN03M_up_arrow_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN03M_up_arrow_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN03M_up_arrow_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN03M_up_arrow_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN04M_down_arrow_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN04M_down_arrow_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN04M_down_arrow_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN04M_down_arrow_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN04M_down_arrow_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN04M_down_arrow_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN07S_select_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN07S_select_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN08S_unselect_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN08S_unselect_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN09S_added {
            get {
                object obj = ResourceManager.GetObject("GE_BTN09S_added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN10L_save_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN10L_save_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN10L_save_DIRTY {
            get {
                object obj = ResourceManager.GetObject("GE_BTN10L_save_DIRTY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN10L_save_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN10L_save_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN10L_save_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN10L_save_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN10L_save_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN10L_save_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN11M_sort_ascend_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN11M_sort_ascend_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN11M_sort_ascend_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN11M_sort_ascend_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN11M_sort_ascend_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN11M_sort_ascend_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN12M_sort_descend_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN12M_sort_descend_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN12M_sort_descend_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN12M_sort_descend_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN12M_sort_descend_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN12M_sort_descend_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN13L_cancel_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN13L_cancel_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN13L_cancel_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN13L_cancel_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN13L_cancel_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN13L_cancel_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14L_preferences_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14L_preferences_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14L_preferences_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14L_preferences_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14L_preferences_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14L_preferences_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14L_preferences_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14L_preferences_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14M_preferences_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14M_preferences_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14M_preferences_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14M_preferences_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN14M_preferences_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN14M_preferences_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN15L_run_sample_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN15L_run_sample_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN15L_run_sample_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN15L_run_sample_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN15L_run_sample_green {
            get {
                object obj = ResourceManager.GetObject("GE_BTN15L_run_sample_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN15L_run_sample_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN15L_run_sample_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN15L_run_sample_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN15L_run_sample_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN16L_settings_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN16L_settings_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN16L_settings_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN16L_settings_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN16L_settings_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN16L_settings_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN16L_settings_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN16L_settings_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN17L_reports_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN17L_reports_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN17L_reports_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN17L_reports_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN17L_reports_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN17L_reports_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN18L_help_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN18L_help_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN18L_help_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN18L_help_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN18L_help_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN18L_help_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN19L_shut_down_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN19L_shut_down_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN19L_shut_down_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN19L_shut_down_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN19L_shut_down_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN19L_shut_down_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN19L_shut_down_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN19L_shut_down_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN20L_ok_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN20L_ok_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN20L_ok_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN20L_ok_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN20L_ok_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN20L_ok_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN21L_left_arrow_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN21L_left_arrow_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN21L_left_arrow_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN21L_left_arrow_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN21L_left_arrow_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN21L_left_arrow_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN21L_left_arrow_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN21L_left_arrow_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN22L_home_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN22L_home_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN22L_home_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN22L_home_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN22L_home_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN22L_home_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN22L_home_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN22L_home_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN23L_protocol_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN23L_protocol_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN23L_protocol_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN23L_protocol_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN23L_protocol_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN23L_protocol_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN23L_protocol_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN23L_protocol_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN24L_progress_CLICK {
            get {
                object obj = ResourceManager.GetObject("GE_BTN24L_progress_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN24L_progress_DISABLE {
            get {
                object obj = ResourceManager.GetObject("GE_BTN24L_progress_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN24L_progress_OVER {
            get {
                object obj = ResourceManager.GetObject("GE_BTN24L_progress_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN24L_progress_STD {
            get {
                object obj = ResourceManager.GetObject("GE_BTN24L_progress_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN25S_marked_as_added {
            get {
                object obj = ResourceManager.GetObject("GE_BTN25S_marked_as_added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN25S_marked_as_deleted {
            get {
                object obj = ResourceManager.GetObject("GE_BTN25S_marked_as_deleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN25S_newly_added {
            get {
                object obj = ResourceManager.GetObject("GE_BTN25S_newly_added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GE_BTN25S_overwritten {
            get {
                object obj = ResourceManager.GetObject("GE_BTN25S_overwritten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GradientBG {
            get {
                object obj = ResourceManager.GetObject("GradientBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN01L_delete_CLCIK {
            get {
                object obj = ResourceManager.GetObject("HM_BTN01L_delete_CLCIK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN01L_delete_OVER {
            get {
                object obj = ResourceManager.GetObject("HM_BTN01L_delete_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN01L_delete_STD {
            get {
                object obj = ResourceManager.GetObject("HM_BTN01L_delete_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN02L_next_CLICK {
            get {
                object obj = ResourceManager.GetObject("HM_BTN02L_next_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN02L_next_OVER {
            get {
                object obj = ResourceManager.GetObject("HM_BTN02L_next_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_BTN02L_next_STD {
            get {
                object obj = ResourceManager.GetObject("HM_BTN02L_next_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_ICON01S_quad_number {
            get {
                object obj = ResourceManager.GetObject("HM_ICON01S_quad_number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HM_ICON02S_volume {
            get {
                object obj = ResourceManager.GetObject("HM_ICON02S_volume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap home_header640x40_bg {
            get {
                object obj = ResourceManager.GetObject("home_header640x40_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_check_green {
            get {
                object obj = ResourceManager.GetObject("L_104x86_check_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_FTP_CLICK {
            get {
                object obj = ResourceManager.GetObject("L_104x86_FTP_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_FTP_OVER {
            get {
                object obj = ResourceManager.GetObject("L_104x86_FTP_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_FTP_STD {
            get {
                object obj = ResourceManager.GetObject("L_104x86_FTP_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_save_green {
            get {
                object obj = ResourceManager.GetObject("L_104x86_save_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_left_CLICK {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_left_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_left_DISABLE {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_left_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_left_OVER {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_left_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_left_STD {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_left_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_right_CLICK {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_right_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_right_DISABLE {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_right_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_right_OVER {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_right_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_single_arrow_right_STD {
            get {
                object obj = ResourceManager.GetObject("L_104x86_single_arrow_right_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_Users_single_CLICK {
            get {
                object obj = ResourceManager.GetObject("L_104x86_Users_single_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_Users_single_DISABLE {
            get {
                object obj = ResourceManager.GetObject("L_104x86_Users_single_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_Users_single_OVER {
            get {
                object obj = ResourceManager.GetObject("L_104x86_Users_single_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap L_104x86_Users_single_STD {
            get {
                object obj = ResourceManager.GetObject("L_104x86_Users_single_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_CLICK {
            get {
                object obj = ResourceManager.GetObject("lock_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_OVER {
            get {
                object obj = ResourceManager.GetObject("lock_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_STD {
            get {
                object obj = ResourceManager.GetObject("lock_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_mainscreen {
            get {
                object obj = ResourceManager.GetObject("logo_mainscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Male75x75 {
            get {
                object obj = ResourceManager.GetObject("Male75x75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoreUsers {
            get {
                object obj = ResourceManager.GetObject("MoreUsers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoreUsersL_CLICK {
            get {
                object obj = ResourceManager.GetObject("MoreUsersL_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoreUsersL_STD {
            get {
                object obj = ResourceManager.GetObject("MoreUsersL_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoreUsersR_CLICK {
            get {
                object obj = ResourceManager.GetObject("MoreUsersR_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoreUsersR_STD {
            get {
                object obj = ResourceManager.GetObject("MoreUsersR_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateDown_CLICK_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateDown_CLICK_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateDown_CLICK_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateDown_CLICK_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateDown_STD_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateDown_STD_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateDown_STD_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateDown_STD_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateLeft_CLICK_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateLeft_CLICK_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateLeft_CLICK_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateLeft_CLICK_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateLeft_STD_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateLeft_STD_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateLeft_STD_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateLeft_STD_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateRight_CLICK_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateRight_CLICK_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateRight_CLICK_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateRight_CLICK_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateRight_STD_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateRight_STD_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateRight_STD_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateRight_STD_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateUp_CLICK_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateUp_CLICK_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateUp_CLICK_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateUp_CLICK_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateUp_STD_65x65 {
            get {
                object obj = ResourceManager.GetObject("NavigateUp_STD_65x65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NavigateUp_STD_65x651 {
            get {
                object obj = ResourceManager.GetObject("NavigateUp_STD_65x651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OneML {
            get {
                object obj = ResourceManager.GetObject("OneML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PF_BTN01S_details_CLICK {
            get {
                object obj = ResourceManager.GetObject("PF_BTN01S_details_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PF_BTN01S_details_OVER {
            get {
                object obj = ResourceManager.GetObject("PF_BTN01S_details_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PF_BTN01S_details_STD {
            get {
                object obj = ResourceManager.GetObject("PF_BTN01S_details_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN07M_volume_next_CLICK {
            get {
                object obj = ResourceManager.GetObject("PR_BTN07M_volume_next_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN07M_volume_next_OVER {
            get {
                object obj = ResourceManager.GetObject("PR_BTN07M_volume_next_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN07M_volume_next_STD {
            get {
                object obj = ResourceManager.GetObject("PR_BTN07M_volume_next_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN08L_add_protocol_CLICK {
            get {
                object obj = ResourceManager.GetObject("PR_BTN08L_add_protocol_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN08L_add_protocol_OVER {
            get {
                object obj = ResourceManager.GetObject("PR_BTN08L_add_protocol_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN08L_add_protocol_STD {
            get {
                object obj = ResourceManager.GetObject("PR_BTN08L_add_protocol_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN09L_remove_protocol_CLICK {
            get {
                object obj = ResourceManager.GetObject("PR_BTN09L_remove_protocol_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN09L_remove_protocol_OVER {
            get {
                object obj = ResourceManager.GetObject("PR_BTN09L_remove_protocol_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PR_BTN09L_remove_protocol_STD {
            get {
                object obj = ResourceManager.GetObject("PR_BTN09L_remove_protocol_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preferences_header_bg {
            get {
                object obj = ResourceManager.GetObject("preferences_header_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PrevArrow {
            get {
                object obj = ResourceManager.GetObject("PrevArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap protocolHeaderBackground {
            get {
                object obj = ResourceManager.GetObject("protocolHeaderBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap QuadrantNumber {
            get {
                object obj = ResourceManager.GetObject("QuadrantNumber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap QuadrantNumber_UNSELECTED {
            get {
                object obj = ResourceManager.GetObject("QuadrantNumber_UNSELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN01R_magnetic {
            get {
                object obj = ResourceManager.GetObject("RE_BTN01R_magnetic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN02R_cocktail {
            get {
                object obj = ResourceManager.GetObject("RE_BTN02R_cocktail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN03R_sample_tube {
            get {
                object obj = ResourceManager.GetObject("RE_BTN03R_sample_tube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN04R_tip_racks {
            get {
                object obj = ResourceManager.GetObject("RE_BTN04R_tip_racks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN05R_seperation {
            get {
                object obj = ResourceManager.GetObject("RE_BTN05R_seperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN06R_waste {
            get {
                object obj = ResourceManager.GetObject("RE_BTN06R_waste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN07R_fraction {
            get {
                object obj = ResourceManager.GetObject("RE_BTN07R_fraction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN08R_buffer_bottle {
            get {
                object obj = ResourceManager.GetObject("RE_BTN08R_buffer_bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN10R_antibody {
            get {
                object obj = ResourceManager.GetObject("RE_BTN10R_antibody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN13N_up_arrow_CLICK {
            get {
                object obj = ResourceManager.GetObject("RE_BTN13N_up_arrow_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN13N_up_arrow_OVER {
            get {
                object obj = ResourceManager.GetObject("RE_BTN13N_up_arrow_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN13N_up_arrow_STD {
            get {
                object obj = ResourceManager.GetObject("RE_BTN13N_up_arrow_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN14N_down_arrow_CLICK {
            get {
                object obj = ResourceManager.GetObject("RE_BTN14N_down_arrow_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN14N_down_arrow_OVER {
            get {
                object obj = ResourceManager.GetObject("RE_BTN14N_down_arrow_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN14N_down_arrow_STD {
            get {
                object obj = ResourceManager.GetObject("RE_BTN14N_down_arrow_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN16L_scan_CLICK {
            get {
                object obj = ResourceManager.GetObject("RE_BTN16L_scan_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN16L_scan_OVER {
            get {
                object obj = ResourceManager.GetObject("RE_BTN16L_scan_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RE_BTN16L_scan_STD {
            get {
                object obj = ResourceManager.GetObject("RE_BTN16L_scan_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResourceButton_GREEN {
            get {
                object obj = ResourceManager.GetObject("ResourceButton_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResourceButton_GREY {
            get {
                object obj = ResourceManager.GetObject("ResourceButton_GREY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResourceButton_PURPLE {
            get {
                object obj = ResourceManager.GetObject("ResourceButton_PURPLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN01L_pause_CLICK {
            get {
                object obj = ResourceManager.GetObject("RN_BTN01L_pause_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN01L_pause_DISABLE {
            get {
                object obj = ResourceManager.GetObject("RN_BTN01L_pause_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN01L_pause_OVER {
            get {
                object obj = ResourceManager.GetObject("RN_BTN01L_pause_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN01L_pause_STD {
            get {
                object obj = ResourceManager.GetObject("RN_BTN01L_pause_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN02L_abort_104x86_CLICK {
            get {
                object obj = ResourceManager.GetObject("RN_BTN02L_abort_104x86_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN02L_abort_104x86_DISABLE {
            get {
                object obj = ResourceManager.GetObject("RN_BTN02L_abort_104x86_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN02L_abort_104x86_OVER {
            get {
                object obj = ResourceManager.GetObject("RN_BTN02L_abort_104x86_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN02L_abort_104x86_STD {
            get {
                object obj = ResourceManager.GetObject("RN_BTN02L_abort_104x86_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN03L_details_CLICK {
            get {
                object obj = ResourceManager.GetObject("RN_BTN03L_details_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN03L_details_OVER {
            get {
                object obj = ResourceManager.GetObject("RN_BTN03L_details_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_BTN03L_details_STD {
            get {
                object obj = ResourceManager.GetObject("RN_BTN03L_details_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RN_ICON01N_overall_progress {
            get {
                object obj = ResourceManager.GetObject("RN_ICON01N_overall_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_Carousel {
            get {
                object obj = ResourceManager.GetObject("RoboSep_Carousel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_CarouselLG {
            get {
                object obj = ResourceManager.GetObject("RoboSep_CarouselLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_Logo {
            get {
                object obj = ResourceManager.GetObject("RoboSep_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sample {
            get {
                object obj = ResourceManager.GetObject("sample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollDOWN_CLICK {
            get {
                object obj = ResourceManager.GetObject("scrollDOWN_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollDOWN_OVER {
            get {
                object obj = ResourceManager.GetObject("scrollDOWN_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollDOWN_STD {
            get {
                object obj = ResourceManager.GetObject("scrollDOWN_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollUP_CLICK {
            get {
                object obj = ResourceManager.GetObject("scrollUP_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollUP_OVER {
            get {
                object obj = ResourceManager.GetObject("scrollUP_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scrollUP_STD {
            get {
                object obj = ResourceManager.GetObject("scrollUP_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SectionDevider {
            get {
                object obj = ResourceManager.GetObject("SectionDevider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap separation {
            get {
                object obj = ResourceManager.GetObject("separation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap splash_animation_fast {
            get {
                object obj = ResourceManager.GetObject("splash_animation_fast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT01L_diagnostic_CLICK {
            get {
                object obj = ResourceManager.GetObject("SR_BT01L_diagnostic_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT01L_diagnostic_DISABLE {
            get {
                object obj = ResourceManager.GetObject("SR_BT01L_diagnostic_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT01L_diagnostic_OVER {
            get {
                object obj = ResourceManager.GetObject("SR_BT01L_diagnostic_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT01L_diagnostic_STD {
            get {
                object obj = ResourceManager.GetObject("SR_BT01L_diagnostic_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT02L_run_logs_CLICK {
            get {
                object obj = ResourceManager.GetObject("SR_BT02L_run_logs_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT02L_run_logs_OVER {
            get {
                object obj = ResourceManager.GetObject("SR_BT02L_run_logs_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT02L_run_logs_STD {
            get {
                object obj = ResourceManager.GetObject("SR_BT02L_run_logs_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT03L_service_menu_CLICK {
            get {
                object obj = ResourceManager.GetObject("SR_BT03L_service_menu_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT03L_service_menu_DISABLE {
            get {
                object obj = ResourceManager.GetObject("SR_BT03L_service_menu_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT03L_service_menu_OVER {
            get {
                object obj = ResourceManager.GetObject("SR_BT03L_service_menu_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT03L_service_menu_STD {
            get {
                object obj = ResourceManager.GetObject("SR_BT03L_service_menu_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT04L_exit_software_CLICK {
            get {
                object obj = ResourceManager.GetObject("SR_BT04L_exit_software_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT04L_exit_software_DISABLE {
            get {
                object obj = ResourceManager.GetObject("SR_BT04L_exit_software_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT04L_exit_software_OVER {
            get {
                object obj = ResourceManager.GetObject("SR_BT04L_exit_software_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SR_BT04L_exit_software_STD {
            get {
                object obj = ResourceManager.GetObject("SR_BT04L_exit_software_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap STDIcon75x75 {
            get {
                object obj = ResourceManager.GetObject("STDIcon75x75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap STEMCELL {
            get {
                object obj = ResourceManager.GetObject("STEMCELL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap STEMCELL1 {
            get {
                object obj = ResourceManager.GetObject("STEMCELL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Textbox_Drowpdown {
            get {
                object obj = ResourceManager.GetObject("Textbox_Drowpdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tipRack {
            get {
                object obj = ResourceManager.GetObject("tipRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unload_eject_CLICK {
            get {
                object obj = ResourceManager.GetObject("unload_eject_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unload_eject_green {
            get {
                object obj = ResourceManager.GetObject("unload_eject_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unload_eject_OVER {
            get {
                object obj = ResourceManager.GetObject("unload_eject_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unload_eject_STD {
            get {
                object obj = ResourceManager.GetObject("unload_eject_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unlock_CLICK {
            get {
                object obj = ResourceManager.GetObject("unlock_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unlock_OVER {
            get {
                object obj = ResourceManager.GetObject("unlock_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap unlock_STD {
            get {
                object obj = ResourceManager.GetObject("unlock_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN01L_clone_user_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN01L_clone_user_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN01L_clone_user_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN01L_clone_user_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN01L_clone_user_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN01L_clone_user_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN02L_add_user_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN02L_add_user_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN02L_add_user_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN02L_add_user_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN02L_add_user_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN02L_add_user_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN03L_remove_user_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN03L_remove_user_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN03L_remove_user_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN03L_remove_user_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN03L_remove_user_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN03L_remove_user_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_hard_drive_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_hard_drive_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_hard_drive_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_hard_drive_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_hard_drive_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_hard_drive_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_add_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_add_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_add_DISABLE {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_add_DISABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_add_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_add_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_add_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_add_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN04L_usb_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN04L_usb_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN05L_edit_user_CLICK {
            get {
                object obj = ResourceManager.GetObject("US_BTN05L_edit_user_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN05L_edit_user_OVER {
            get {
                object obj = ResourceManager.GetObject("US_BTN05L_edit_user_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap US_BTN05L_edit_user_STD {
            get {
                object obj = ResourceManager.GetObject("US_BTN05L_edit_user_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap USB_framed {
            get {
                object obj = ResourceManager.GetObject("USB_framed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap USBIcon {
            get {
                object obj = ResourceManager.GetObject("USBIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap User_header_bg {
            get {
                object obj = ResourceManager.GetObject("User_header_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap User_HeaderSml2 {
            get {
                object obj = ResourceManager.GetObject("User_HeaderSml2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UserIcon01 {
            get {
                object obj = ResourceManager.GetObject("UserIcon01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap waste {
            get {
                object obj = ResourceManager.GetObject("waste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowClose_CLICK {
            get {
                object obj = ResourceManager.GetObject("WindowClose_CLICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowClose_STD {
            get {
                object obj = ResourceManager.GetObject("WindowClose_STD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
