//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _1ml {
            get {
                object obj = ResourceManager.GetObject("1ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_EditProtocolList {
            get {
                object obj = ResourceManager.GetObject("BG_EditProtocolList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_HEXGRID {
            get {
                object obj = ResourceManager.GetObject("BG_HEXGRID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_PANEL_BORDER {
            get {
                object obj = ResourceManager.GetObject("BG_PANEL_BORDER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_ProtocolSelection {
            get {
                object obj = ResourceManager.GetObject("BG_ProtocolSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_Resources {
            get {
                object obj = ResourceManager.GetObject("BG_Resources", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_Resources1 {
            get {
                object obj = ResourceManager.GetObject("BG_Resources1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BG_SearchBar {
            get {
                object obj = ResourceManager.GetObject("BG_SearchBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bigRectButton {
            get {
                object obj = ResourceManager.GetObject("bigRectButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_ABBORT0 {
            get {
                object obj = ResourceManager.GetObject("Button_ABBORT0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_ABBORT1 {
            get {
                object obj = ResourceManager.GetObject("Button_ABBORT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_ABBORT2 {
            get {
                object obj = ResourceManager.GetObject("Button_ABBORT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_ABBORT3 {
            get {
                object obj = ResourceManager.GetObject("Button_ABBORT3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ACCEPT0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ACCEPT0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ACCEPT1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ACCEPT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ACCEPT2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ACCEPT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ACCEPT3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ACCEPT3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ADDPROFILE0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ADDPROFILE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ADDPROFILE1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ADDPROFILE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ADDPROFILE2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ADDPROFILE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_ADDPROFILE3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_ADDPROFILE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_CANCEL0 {
            get {
                object obj = ResourceManager.GetObject("Button_CANCEL0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_CANCEL1 {
            get {
                object obj = ResourceManager.GetObject("Button_CANCEL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_DOWN_Disable {
            get {
                object obj = ResourceManager.GetObject("BUTTON_DOWN_Disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_DOWN0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_DOWN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_DOWN1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_DOWN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_DOWN2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_DOWN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_DOWN3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_DOWN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Filter {
            get {
                object obj = ResourceManager.GetObject("Button_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Filter2 {
            get {
                object obj = ResourceManager.GetObject("Button_Filter2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Home0 {
            get {
                object obj = ResourceManager.GetObject("Button_Home0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Home1 {
            get {
                object obj = ResourceManager.GetObject("Button_Home1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Home2 {
            get {
                object obj = ResourceManager.GetObject("Button_Home2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Home3 {
            get {
                object obj = ResourceManager.GetObject("Button_Home3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HOMECANCEL0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HOMECANCEL0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HOMECANCEL1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HOMECANCEL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN2a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN2a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_HUMAN3a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_HUMAN3a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE21 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MOUSE31 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MOUSE31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MYPROFILE0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MYPROFILE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MYPROFILE1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MYPROFILE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MYPROFILE2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MYPROFILE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_MYPROFILE3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_MYPROFILE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE2a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE2a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE2a___Copy {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE2a - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_NEGATIVE3a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_NEGATIVE3a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PACKAGE0 {
            get {
                object obj = ResourceManager.GetObject("Button_PACKAGE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PACKAGE1 {
            get {
                object obj = ResourceManager.GetObject("Button_PACKAGE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PACKAGE2 {
            get {
                object obj = ResourceManager.GetObject("Button_PACKAGE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PACKAGE3 {
            get {
                object obj = ResourceManager.GetObject("Button_PACKAGE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE2a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE2a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_POSITIVE3a {
            get {
                object obj = ResourceManager.GetObject("BUTTON_POSITIVE3a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_PROMPTBUTTON0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_PROMPTBUTTON3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLEDITOR0 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLEDITOR0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLEDITOR1 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLEDITOR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLEDITOR2 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLEDITOR2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLEDITOR3 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLEDITOR3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLLIST0 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLLIST0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLLIST1 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLLIST1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLLIST2 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLLIST2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_PROTOCOLLIST3 {
            get {
                object obj = ResourceManager.GetObject("Button_PROTOCOLLIST3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_QUADRANTCANCEL {
            get {
                object obj = ResourceManager.GetObject("Button_QUADRANTCANCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT_Disable {
            get {
                object obj = ResourceManager.GetObject("Button_RECT_Disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT_MED0 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT_MED0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT_MED1 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT_MED1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT_MED2 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT_MED2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT_MED3 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT_MED3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT0 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT1 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT2 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RECT3 {
            get {
                object obj = ResourceManager.GetObject("Button_RECT3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_REMOVEPROTOCOL0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_REMOVEPROTOCOL0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_REMOVEPROTOCOL1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_REMOVEPROTOCOL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_REMOVEPROTOCOL2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_REMOVEPROTOCOL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_REMOVEPROTOCOL3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_REMOVEPROTOCOL3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_RESOURCE_LIST0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_RESOURCE_LIST0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_RESOURCE_LIST1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_RESOURCE_LIST1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_RESOURCE_LIST2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_RESOURCE_LIST2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_RESOURCE_LIST3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_RESOURCE_LIST3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_RESOURCE_Selected {
            get {
                object obj = ResourceManager.GetObject("BUTTON_RESOURCE_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RUN0 {
            get {
                object obj = ResourceManager.GetObject("Button_RUN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RUN1 {
            get {
                object obj = ResourceManager.GetObject("Button_RUN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RUN2 {
            get {
                object obj = ResourceManager.GetObject("Button_RUN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_RUN3 {
            get {
                object obj = ResourceManager.GetObject("Button_RUN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SAVELIST0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SAVELIST0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SAVELIST1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SAVELIST1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SAVELIST2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SAVELIST2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SAVELIST3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SAVELIST3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SELECTPROTOCOL_ALLMY0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SELECTPROTOCOL_ALLMY0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SELECTPROTOCOL_ALLMY1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SELECTPROTOCOL_ALLMY1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SELECTPROTOCOL_ALLMY2 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SELECTPROTOCOL_ALLMY2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_SELECTPROTOCOL_ALLMY3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_SELECTPROTOCOL_ALLMY3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SERVICE0 {
            get {
                object obj = ResourceManager.GetObject("Button_SERVICE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SERVICE1 {
            get {
                object obj = ResourceManager.GetObject("Button_SERVICE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SERVICE2 {
            get {
                object obj = ResourceManager.GetObject("Button_SERVICE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SERVICE3 {
            get {
                object obj = ResourceManager.GetObject("Button_SERVICE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SHUTDOWN0 {
            get {
                object obj = ResourceManager.GetObject("Button_SHUTDOWN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SHUTDOWN1 {
            get {
                object obj = ResourceManager.GetObject("Button_SHUTDOWN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SHUTDOWN2 {
            get {
                object obj = ResourceManager.GetObject("Button_SHUTDOWN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_SHUTDOWN3 {
            get {
                object obj = ResourceManager.GetObject("Button_SHUTDOWN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Switch {
            get {
                object obj = ResourceManager.GetObject("Button_Switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_Switch2 {
            get {
                object obj = ResourceManager.GetObject("Button_Switch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_UP_Disable {
            get {
                object obj = ResourceManager.GetObject("BUTTON_UP_Disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_UP0 {
            get {
                object obj = ResourceManager.GetObject("Button_UP0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_UP1 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_UP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_UP2 {
            get {
                object obj = ResourceManager.GetObject("Button_UP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BUTTON_UP3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_UP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_USBLOAD0 {
            get {
                object obj = ResourceManager.GetObject("Button_USBLOAD0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_USBLOAD1 {
            get {
                object obj = ResourceManager.GetObject("Button_USBLOAD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_USBLOAD2 {
            get {
                object obj = ResourceManager.GetObject("Button_USBLOAD2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Button_USBLOAD3 {
            get {
                object obj = ResourceManager.GetObject("Button_USBLOAD3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_Antibody {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_Antibody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_AntibodyG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_AntibodyG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_AntibodySelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_AntibodySelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_Magnet {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_Magnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_MagnetG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_MagnetG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_MagneticParticle {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_MagneticParticle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_MagneticParticleG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_MagneticParticleG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_MagneticParticleSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_MagneticParticleSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_MagnetSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_MagnetSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeFraction {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeFraction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeFractionG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeFractionG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeFractionSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeFractionSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeSelection {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeSelectionG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeSelectionG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_NegativeSelectionSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_NegativeSelectionSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_Sample {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_Sample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_SampleG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_SampleG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_SampleSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_SampleSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_TipRack {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_TipRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_TipRackG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_TipRackG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_TipRackSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_TipRackSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_Waste {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_Waste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_WasteG {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_WasteG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Carousel_Section_WasteSelect {
            get {
                object obj = ResourceManager.GetObject("Carousel_Section_WasteSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CheckBox {
            get {
                object obj = ResourceManager.GetObject("CheckBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CHECKBOX0 {
            get {
                object obj = ResourceManager.GetObject("CHECKBOX0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CHECKBOX1 {
            get {
                object obj = ResourceManager.GetObject("CHECKBOX1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Close_Dashboard {
            get {
                object obj = ResourceManager.GetObject("Close_Dashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Close_Dashboard1 {
            get {
                object obj = ResourceManager.GetObject("Close_Dashboard1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Dashboard_HexDashboard {
            get {
                object obj = ResourceManager.GetObject("Dashboard_HexDashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Dashboard_Sampling {
            get {
                object obj = ResourceManager.GetObject("Dashboard_Sampling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbBack {
            get {
                object obj = ResourceManager.GetObject("fbBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbBack3 {
            get {
                object obj = ResourceManager.GetObject("fbBack3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbButton0 {
            get {
                object obj = ResourceManager.GetObject("fbButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbButton3 {
            get {
                object obj = ResourceManager.GetObject("fbButton3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbRefresh {
            get {
                object obj = ResourceManager.GetObject("fbRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbRefresh3 {
            get {
                object obj = ResourceManager.GetObject("fbRefresh3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbUp {
            get {
                object obj = ResourceManager.GetObject("fbUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fbUp3 {
            get {
                object obj = ResourceManager.GetObject("fbUp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fileBrowser {
            get {
                object obj = ResourceManager.GetObject("fileBrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Frame_Background {
            get {
                object obj = ResourceManager.GetObject("Frame_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_HELP0 {
            get {
                object obj = ResourceManager.GetObject("HEX_HELP0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_HELP1 {
            get {
                object obj = ResourceManager.GetObject("HEX_HELP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_HELP2 {
            get {
                object obj = ResourceManager.GetObject("HEX_HELP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_HELP3 {
            get {
                object obj = ResourceManager.GetObject("HEX_HELP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_LOG0 {
            get {
                object obj = ResourceManager.GetObject("HEX_LOG0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_LOG1 {
            get {
                object obj = ResourceManager.GetObject("HEX_LOG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_LOG2 {
            get {
                object obj = ResourceManager.GetObject("HEX_LOG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_LOG3 {
            get {
                object obj = ResourceManager.GetObject("HEX_LOG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_PROTOCOLS0 {
            get {
                object obj = ResourceManager.GetObject("HEX_PROTOCOLS0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_PROTOCOLS1 {
            get {
                object obj = ResourceManager.GetObject("HEX_PROTOCOLS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_PROTOCOLS2 {
            get {
                object obj = ResourceManager.GetObject("HEX_PROTOCOLS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_PROTOCOLS3 {
            get {
                object obj = ResourceManager.GetObject("HEX_PROTOCOLS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SAMPLE0 {
            get {
                object obj = ResourceManager.GetObject("HEX_SAMPLE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SAMPLE1 {
            get {
                object obj = ResourceManager.GetObject("HEX_SAMPLE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SAMPLE2 {
            get {
                object obj = ResourceManager.GetObject("HEX_SAMPLE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SAMPLE3 {
            get {
                object obj = ResourceManager.GetObject("HEX_SAMPLE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SERVICE0 {
            get {
                object obj = ResourceManager.GetObject("HEX_SERVICE0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SERVICE1 {
            get {
                object obj = ResourceManager.GetObject("HEX_SERVICE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SERVICE2 {
            get {
                object obj = ResourceManager.GetObject("HEX_SERVICE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SERVICE3 {
            get {
                object obj = ResourceManager.GetObject("HEX_SERVICE3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SHUTDOWN0 {
            get {
                object obj = ResourceManager.GetObject("HEX_SHUTDOWN0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SHUTDOWN1 {
            get {
                object obj = ResourceManager.GetObject("HEX_SHUTDOWN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SHUTDOWN2 {
            get {
                object obj = ResourceManager.GetObject("HEX_SHUTDOWN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SHUTDOWN3 {
            get {
                object obj = ResourceManager.GetObject("HEX_SHUTDOWN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SYSTEM0 {
            get {
                object obj = ResourceManager.GetObject("HEX_SYSTEM0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SYSTEM1 {
            get {
                object obj = ResourceManager.GetObject("HEX_SYSTEM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SYSTEM2 {
            get {
                object obj = ResourceManager.GetObject("HEX_SYSTEM2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HEX_SYSTEM3 {
            get {
                object obj = ResourceManager.GetObject("HEX_SYSTEM3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HexButton0 {
            get {
                object obj = ResourceManager.GetObject("HexButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HexButton1 {
            get {
                object obj = ResourceManager.GetObject("HexButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HexButton2 {
            get {
                object obj = ResourceManager.GetObject("HexButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HexButton3 {
            get {
                object obj = ResourceManager.GetObject("HexButton3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HomeButton {
            get {
                object obj = ResourceManager.GetObject("HomeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_L0 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_L0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_L1 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_M0 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_M0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_M1 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_M1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_R0 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_R0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KeybaordButton_R1 {
            get {
                object obj = ResourceManager.GetObject("KeybaordButton_R1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KEYBOARD_ENTER0 {
            get {
                object obj = ResourceManager.GetObject("KEYBOARD_ENTER0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KEYBOARD_ENTER1 {
            get {
                object obj = ResourceManager.GetObject("KEYBOARD_ENTER1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PillButton {
            get {
                object obj = ResourceManager.GetObject("PillButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect10 {
            get {
                object obj = ResourceManager.GetObject("Qselect10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect11 {
            get {
                object obj = ResourceManager.GetObject("Qselect11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect12 {
            get {
                object obj = ResourceManager.GetObject("Qselect12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect20 {
            get {
                object obj = ResourceManager.GetObject("Qselect20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect21 {
            get {
                object obj = ResourceManager.GetObject("Qselect21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect22 {
            get {
                object obj = ResourceManager.GetObject("Qselect22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect30 {
            get {
                object obj = ResourceManager.GetObject("Qselect30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect31 {
            get {
                object obj = ResourceManager.GetObject("Qselect31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect32 {
            get {
                object obj = ResourceManager.GetObject("Qselect32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect40 {
            get {
                object obj = ResourceManager.GetObject("Qselect40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect41 {
            get {
                object obj = ResourceManager.GetObject("Qselect41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Qselect42 {
            get {
                object obj = ResourceManager.GetObject("Qselect42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant {
            get {
                object obj = ResourceManager.GetObject("Quadrant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant_Grey2 {
            get {
                object obj = ResourceManager.GetObject("Quadrant_Grey2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant_Purple {
            get {
                object obj = ResourceManager.GetObject("Quadrant_Purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant1 {
            get {
                object obj = ResourceManager.GetObject("Quadrant1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant2 {
            get {
                object obj = ResourceManager.GetObject("Quadrant2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant3 {
            get {
                object obj = ResourceManager.GetObject("Quadrant3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Quadrant4 {
            get {
                object obj = ResourceManager.GetObject("Quadrant4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap QuadrantAll {
            get {
                object obj = ResourceManager.GetObject("QuadrantAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboMessagePanel_BL {
            get {
                object obj = ResourceManager.GetObject("RoboMessagePanel_BL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboMessagePanel_BR {
            get {
                object obj = ResourceManager.GetObject("RoboMessagePanel_BR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboMessagePanel_TL {
            get {
                object obj = ResourceManager.GetObject("RoboMessagePanel_TL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboMessagePanel_TR {
            get {
                object obj = ResourceManager.GetObject("RoboMessagePanel_TR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_BL {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_BL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_BOTTOMLEFT {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_BOTTOMLEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_BOTTOMRIGHT {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_BOTTOMRIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_BR {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_BR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_TL {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_TL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_TOPLEFT {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_TOPLEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_TOPRIGHT {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_TOPRIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboPANEL_CORNER_TR {
            get {
                object obj = ResourceManager.GetObject("RoboPANEL_CORNER_TR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_Splash_640x480 {
            get {
                object obj = ResourceManager.GetObject("RoboSep_Splash_640x480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_SplashAnim_640x480 {
            get {
                object obj = ResourceManager.GetObject("RoboSep_SplashAnim_640x480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RoboSep_SplashAnim_640x480a {
            get {
                object obj = ResourceManager.GetObject("RoboSep_SplashAnim_640x480a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SampleTube {
            get {
                object obj = ResourceManager.GetObject("SampleTube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SmallPink {
            get {
                object obj = ResourceManager.GetObject("SmallPink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spacer_ProtocolSelect {
            get {
                object obj = ResourceManager.GetObject("spacer_ProtocolSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Bottom {
            get {
                object obj = ResourceManager.GetObject("Tab_Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_bottom1 {
            get {
                object obj = ResourceManager.GetObject("Tab_bottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_bottom2 {
            get {
                object obj = ResourceManager.GetObject("Tab_bottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_bottom3 {
            get {
                object obj = ResourceManager.GetObject("Tab_bottom3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_HELPVIDEO1 {
            get {
                object obj = ResourceManager.GetObject("TAB_HELPVIDEO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_HELPVIDEO2 {
            get {
                object obj = ResourceManager.GetObject("TAB_HELPVIDEO2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_mid1 {
            get {
                object obj = ResourceManager.GetObject("Tab_mid1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_mid2 {
            get {
                object obj = ResourceManager.GetObject("Tab_mid2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_mid3 {
            get {
                object obj = ResourceManager.GetObject("Tab_mid3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Middle_jpg {
            get {
                object obj = ResourceManager.GetObject("Tab_Middle_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_REPORTS1 {
            get {
                object obj = ResourceManager.GetObject("TAB_REPORTS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_REPORTS2 {
            get {
                object obj = ResourceManager.GetObject("TAB_REPORTS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_REPORTS3 {
            get {
                object obj = ResourceManager.GetObject("TAB_REPORTS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_ROBOSEP1 {
            get {
                object obj = ResourceManager.GetObject("TAB_ROBOSEP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_ROBOSEP2 {
            get {
                object obj = ResourceManager.GetObject("TAB_ROBOSEP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_RUNSTAT1 {
            get {
                object obj = ResourceManager.GetObject("TAB_RUNSTAT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_RUNSTAT2 {
            get {
                object obj = ResourceManager.GetObject("TAB_RUNSTAT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_RUNSTAT3 {
            get {
                object obj = ResourceManager.GetObject("TAB_RUNSTAT3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Top {
            get {
                object obj = ResourceManager.GetObject("Tab_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Top1 {
            get {
                object obj = ResourceManager.GetObject("Tab_Top1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Top2 {
            get {
                object obj = ResourceManager.GetObject("Tab_Top2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Tab_Top3 {
            get {
                object obj = ResourceManager.GetObject("Tab_Top3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_VIDLOG1 {
            get {
                object obj = ResourceManager.GetObject("TAB_VIDLOG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_VIDLOG2 {
            get {
                object obj = ResourceManager.GetObject("TAB_VIDLOG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TAB_VIDLOG3 {
            get {
                object obj = ResourceManager.GetObject("TAB_VIDLOG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TextBox_Login {
            get {
                object obj = ResourceManager.GetObject("TextBox_Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TipRack {
            get {
                object obj = ResourceManager.GetObject("TipRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TOGGLE_QUADRANT0 {
            get {
                object obj = ResourceManager.GetObject("TOGGLE_QUADRANT0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TOGGLE_QUADRANT1 {
            get {
                object obj = ResourceManager.GetObject("TOGGLE_QUADRANT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TOGGLE_QUADRANT2 {
            get {
                object obj = ResourceManager.GetObject("TOGGLE_QUADRANT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WasteTube {
            get {
                object obj = ResourceManager.GetObject("WasteTube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
