//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesla.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tesla.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AbortButton0 {
            get {
                object obj = ResourceManager.GetObject("AbortButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AbortButton1 {
            get {
                object obj = ResourceManager.GetObject("AbortButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AbortButton2 {
            get {
                object obj = ResourceManager.GetObject("AbortButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AbortButtonDisable {
            get {
                object obj = ResourceManager.GetObject("AbortButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AcceptButton0 {
            get {
                object obj = ResourceManager.GetObject("AcceptButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AcceptButton1 {
            get {
                object obj = ResourceManager.GetObject("AcceptButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AcceptButton2 {
            get {
                object obj = ResourceManager.GetObject("AcceptButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AcceptButtonDisable {
            get {
                object obj = ResourceManager.GetObject("AcceptButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AxisControlBG {
            get {
                object obj = ResourceManager.GetObject("AxisControlBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackButton0 {
            get {
                object obj = ResourceManager.GetObject("BackButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackButton1 {
            get {
                object obj = ResourceManager.GetObject("BackButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackButton2 {
            get {
                object obj = ResourceManager.GetObject("BackButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackButtonDisable {
            get {
                object obj = ResourceManager.GetObject("BackButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode_0 {
            get {
                object obj = ResourceManager.GetObject("barcode_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode_1 {
            get {
                object obj = ResourceManager.GetObject("barcode_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode_2 {
            get {
                object obj = ResourceManager.GetObject("barcode_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode_inactive {
            get {
                object obj = ResourceManager.GetObject("barcode_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BUTTON_PROMPTBUTTON_BLACK_BIG0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON_BLACK_BIG0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BUTTON_PROMPTBUTTON_BLACK_BIG3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON_BLACK_BIG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BUTTON_PROMPTBUTTON_BLACK0 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON_BLACK0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BUTTON_PROMPTBUTTON_BLACK3 {
            get {
                object obj = ResourceManager.GetObject("BUTTON_PROMPTBUTTON_BLACK3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Carousel0 {
            get {
                object obj = ResourceManager.GetObject("Carousel0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Carousel1 {
            get {
                object obj = ResourceManager.GetObject("Carousel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Carousel2 {
            get {
                object obj = ResourceManager.GetObject("Carousel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CarouselCClockwise0 {
            get {
                object obj = ResourceManager.GetObject("CarouselCClockwise0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CarouselCClockwise1 {
            get {
                object obj = ResourceManager.GetObject("CarouselCClockwise1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CarouselClockwise0 {
            get {
                object obj = ResourceManager.GetObject("CarouselClockwise0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CarouselClockwise1 {
            get {
                object obj = ResourceManager.GetObject("CarouselClockwise1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CourseFine0 {
            get {
                object obj = ResourceManager.GetObject("CourseFine0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CourseFine1 {
            get {
                object obj = ResourceManager.GetObject("CourseFine1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CourseFine2 {
            get {
                object obj = ResourceManager.GetObject("CourseFine2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HardwareInfoBG {
            get {
                object obj = ResourceManager.GetObject("HardwareInfoBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpTabPanel {
            get {
                object obj = ResourceManager.GetObject("HelpTabPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_0 {
            get {
                object obj = ResourceManager.GetObject("LED_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_1 {
            get {
                object obj = ResourceManager.GetObject("LED_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_2 {
            get {
                object obj = ResourceManager.GetObject("LED_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_test {
            get {
                object obj = ResourceManager.GetObject("login_test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainMenuSelectionBridge {
            get {
                object obj = ResourceManager.GetObject("MainMenuSelectionBridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageDownButton0 {
            get {
                object obj = ResourceManager.GetObject("PageDownButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageDownButton1 {
            get {
                object obj = ResourceManager.GetObject("PageDownButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageDownButton2 {
            get {
                object obj = ResourceManager.GetObject("PageDownButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageDownButtonDisable {
            get {
                object obj = ResourceManager.GetObject("PageDownButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageUpButton0 {
            get {
                object obj = ResourceManager.GetObject("PageUpButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageUpButton1 {
            get {
                object obj = ResourceManager.GetObject("PageUpButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageUpButton2 {
            get {
                object obj = ResourceManager.GetObject("PageUpButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageUpButtonDisable {
            get {
                object obj = ResourceManager.GetObject("PageUpButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreButton0 {
            get {
                object obj = ResourceManager.GetObject("RestoreButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreButton1 {
            get {
                object obj = ResourceManager.GetObject("RestoreButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreButton2 {
            get {
                object obj = ResourceManager.GetObject("RestoreButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreButtonDisable {
            get {
                object obj = ResourceManager.GetObject("RestoreButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap robosep_service_background {
            get {
                object obj = ResourceManager.GetObject("robosep_service_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServiceBG {
            get {
                object obj = ResourceManager.GetObject("ServiceBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serviceMenu_0 {
            get {
                object obj = ResourceManager.GetObject("serviceMenu_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serviceMenu_1 {
            get {
                object obj = ResourceManager.GetObject("serviceMenu_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serviceMenu_2 {
            get {
                object obj = ResourceManager.GetObject("serviceMenu_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServiceMenuBG {
            get {
                object obj = ResourceManager.GetObject("ServiceMenuBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServicePanel {
            get {
                object obj = ResourceManager.GetObject("ServicePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepSize {
            get {
                object obj = ResourceManager.GetObject("stepSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stripper0 {
            get {
                object obj = ResourceManager.GetObject("Stripper0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stripper1 {
            get {
                object obj = ResourceManager.GetObject("Stripper1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stripper2 {
            get {
                object obj = ResourceManager.GetObject("Stripper2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripperIn0 {
            get {
                object obj = ResourceManager.GetObject("StripperIn0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripperIn1 {
            get {
                object obj = ResourceManager.GetObject("StripperIn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripperOut0 {
            get {
                object obj = ResourceManager.GetObject("StripperOut0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripperOut1 {
            get {
                object obj = ResourceManager.GetObject("StripperOut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theta0 {
            get {
                object obj = ResourceManager.GetObject("Theta0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theta1 {
            get {
                object obj = ResourceManager.GetObject("Theta1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theta2 {
            get {
                object obj = ResourceManager.GetObject("Theta2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThetaLeft0 {
            get {
                object obj = ResourceManager.GetObject("ThetaLeft0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThetaLeft1 {
            get {
                object obj = ResourceManager.GetObject("ThetaLeft1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThetaRight0 {
            get {
                object obj = ResourceManager.GetObject("ThetaRight0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThetaRight1 {
            get {
                object obj = ResourceManager.GetObject("ThetaRight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArm0 {
            get {
                object obj = ResourceManager.GetObject("VertArm0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArm1 {
            get {
                object obj = ResourceManager.GetObject("VertArm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArm2 {
            get {
                object obj = ResourceManager.GetObject("VertArm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArmDown0 {
            get {
                object obj = ResourceManager.GetObject("VertArmDown0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArmDown1 {
            get {
                object obj = ResourceManager.GetObject("VertArmDown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArmUp0 {
            get {
                object obj = ResourceManager.GetObject("VertArmUp0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VertArmUp1 {
            get {
                object obj = ResourceManager.GetObject("VertArmUp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_0 {
            get {
                object obj = ResourceManager.GetObject("video_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_1 {
            get {
                object obj = ResourceManager.GetObject("video_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_2 {
            get {
                object obj = ResourceManager.GetObject("video_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_inactive {
            get {
                object obj = ResourceManager.GetObject("video_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
